name: CD workflow

on: [push]

jobs:
  linting-and-unit-tests:
    uses: ./.github/workflows/ci-operations.yaml
  build:
    runs-on: ubuntu-latest
    needs: [linting-and-unit-tests]
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --tag project-management-dashboard:$(date +%s)
