name: CI workflow

on: [push]

jobs:
  linting-steps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install isort black flake8

      - name: Code format check with isort and black
        run: |
          isort . --check-only
          black . -check

      - name: Check code style with flake8
        run: |
          flake8 .
