name: CI workflow

on: [workflow_call]

jobs:
  linting-steps:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install isort black flake8

      - name: Code format check with isort and black
        continue-on-error: true
        run: |
          isort . --check-only
          black . -check

      - name: Check code style with flake8
        continue-on-error: true
        run: |
          flake8 .

  testing:
    environment: CI-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          LOCAL_STORAGE: ${{ secrets.LOCAL_STORAGE }}
          AUTH_SECRET_KEY: ${{ secrets.AUTH_SECRET_KEY }}
          JOIN_SECRET_KEY: ${{ secrets.JOIN_SECRET_KEY }}
          RAW_LOGO_BUCKET: ${{ secrets.RAW_LOGO_BUCKET }}
          RESIZED_LOGO_BUCKET: ${{ secrets.RESIZED_LOGO_BUCKET }}
          DOCUMENTS_BUCKET: ${{ secrets.DOCUMENTS_BUCKET }}
          LOG_FILE_PATH: ${{ secrets.LOG_FILE_PATH }}
        run: python -m unittest discover tests
